import { send_message } from "../telegram/telegram.js";
import { fetchCgvSchedule } from "./cgv.js";
import { findEarliestScreening } from "./utils.js"
import 'dotenv/config'

const params = new URLSearchParams({
  coCd: process.env.CO_CD,
  siteNo: process.env.SITE_NUMBER,
  rtctlScopCd: process.env.RELEASE_CONTROL_SCOPE_CODE,
  scnYmd: process.env.SCREEN_YMD
});
const BASE_URL = `${process.env.CGV_URL}?${params}`;
const MOVIE_MIN_TIME = process.env.MOVIE_MIN_TIME;
const MOVIE_MAX_TIME = process.env.MOVIE_MAX_TIME;
const SCREENS_NUMBER = process.env.SCREENS_NUMBER;

let previous = null;

export async function checking() {
  await send_message("CGV 감시 시작 👀");

  while (true) {
    const data = await fetchCgvSchedule(BASE_URL);
    const current = JSON.stringify(data.data);

    if (previous && previous !== current) {
      const result = findEarliestScreening(
        data.data,
        SCREENS_NUMBER,
        MOVIE_MIN_TIME,
        MOVIE_MAX_TIME
      );
      if (result) {
        return result;
      }
      send_message("상영관은 열렸지만 선택한 것은 없음.")
    }
    previous = current;
    await new Promise(resolve => setTimeout(resolve, 5000));
  }
}

// const tempData = {
//   "statusCode": 0,
//   "statusMessage": "조회 되었습니다.",
//   "data": [
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "001",
//       "scnsNm": "1관 (Laser)",
//       "expoScnsNm": "1관 (Hamilton Watch Odyssey)",
//       "scnsEnm": "CINEMA 1",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "1",
//       "prodNo": "20054562",
//       "expoProdNm": "오디세이",
//       "engProdNm": "The Odyssey",
//       "prodNm": "오디세이",
//       "movkndCd": "02",
//       "movkndDsplNm": "2D",
//       "movkndDsplEnm": "2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "01",
//       "salsTznNm": "모닝",
//       "scnsrtTm": "0730",
//       "scnendTm": "1032",
//       "salEndTm": "0745",
//       "sascnsGradCd": "01",
//       "sortOseq": "5",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "01",
//       "tcscnsGradNm": "일반",
//       "stcnt": "204",
//       "cpSeatCnt": "204",
//       "frSeatCnt": "143",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "2",
//       "movfNo": "50002601",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0101",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "144",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "0740",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "001",
//       "scnsNm": "1관 (Laser)",
//       "expoScnsNm": "1관 (Hamilton Watch Odyssey)",
//       "scnsEnm": "CINEMA 1",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "2",
//       "prodNo": "20054562",
//       "expoProdNm": "오디세이",
//       "engProdNm": "The Odyssey",
//       "prodNm": "오디세이",
//       "movkndCd": "02",
//       "movkndDsplNm": "2D",
//       "movkndDsplEnm": "2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "24",
//       "salsTznNm": "브런치",
//       "scnsrtTm": "1100",
//       "scnendTm": "1402",
//       "salEndTm": "1115",
//       "sascnsGradCd": "01",
//       "sortOseq": "5",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "01",
//       "tcscnsGradNm": "일반",
//       "stcnt": "204",
//       "cpSeatCnt": "204",
//       "frSeatCnt": "154",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "2",
//       "movfNo": "50002601",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0101",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "154",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1110",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "001",
//       "scnsNm": "1관 (Laser)",
//       "expoScnsNm": "1관 (Hamilton Watch Odyssey)",
//       "scnsEnm": "CINEMA 1",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "3",
//       "prodNo": "20054562",
//       "expoProdNm": "오디세이",
//       "engProdNm": "The Odyssey",
//       "prodNm": "오디세이",
//       "movkndCd": "02",
//       "movkndDsplNm": "2D",
//       "movkndDsplEnm": "2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "1430",
//       "scnendTm": "1732",
//       "salEndTm": "1445",
//       "sascnsGradCd": "01",
//       "sortOseq": "5",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "01",
//       "tcscnsGradNm": "일반",
//       "stcnt": "204",
//       "cpSeatCnt": "204",
//       "frSeatCnt": "143",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "2",
//       "movfNo": "50002601",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0101",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "143",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1440",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "001",
//       "scnsNm": "1관 (Laser)",
//       "expoScnsNm": "1관 (Hamilton Watch Odyssey)",
//       "scnsEnm": "CINEMA 1",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "4",
//       "prodNo": "20054562",
//       "expoProdNm": "오디세이",
//       "engProdNm": "The Odyssey",
//       "prodNm": "오디세이",
//       "movkndCd": "02",
//       "movkndDsplNm": "2D",
//       "movkndDsplEnm": "2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "1800",
//       "scnendTm": "2102",
//       "salEndTm": "1815",
//       "sascnsGradCd": "01",
//       "sortOseq": "5",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "01",
//       "tcscnsGradNm": "일반",
//       "stcnt": "204",
//       "cpSeatCnt": "204",
//       "frSeatCnt": "127",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "2",
//       "movfNo": "50002601",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0101",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "127",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1810",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "001",
//       "scnsNm": "1관 (Laser)",
//       "expoScnsNm": "1관 (Hamilton Watch Odyssey)",
//       "scnsEnm": "CINEMA 1",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "5",
//       "prodNo": "20054562",
//       "expoProdNm": "오디세이",
//       "engProdNm": "The Odyssey",
//       "prodNm": "오디세이",
//       "movkndCd": "02",
//       "movkndDsplNm": "2D",
//       "movkndDsplEnm": "2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "2130",
//       "scnendTm": "2432",
//       "salEndTm": "2145",
//       "sascnsGradCd": "01",
//       "sortOseq": "5",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "01",
//       "tcscnsGradNm": "일반",
//       "stcnt": "204",
//       "cpSeatCnt": "204",
//       "frSeatCnt": "191",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "2",
//       "movfNo": "50002601",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0101",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "191",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "2140",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "001",
//       "scnsNm": "1관 (Laser)",
//       "expoScnsNm": "1관 (Hamilton Watch Odyssey)",
//       "scnsEnm": "CINEMA 1",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "6",
//       "prodNo": "20054562",
//       "expoProdNm": "오디세이",
//       "engProdNm": "The Odyssey",
//       "prodNm": "오디세이",
//       "movkndCd": "02",
//       "movkndDsplNm": "2D",
//       "movkndDsplEnm": "2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "2500",
//       "scnendTm": "2802",
//       "salEndTm": "2515",
//       "sascnsGradCd": "01",
//       "sortOseq": "5",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "01",
//       "tcscnsGradNm": "일반",
//       "stcnt": "204",
//       "cpSeatCnt": "204",
//       "frSeatCnt": "204",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "2",
//       "movfNo": "50002601",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0101",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "204",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "2510",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "003",
//       "scnsNm": "4DX관",
//       "expoScnsNm": "4DX관",
//       "scnsEnm": "4DX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "2",
//       "prodNo": "20054744",
//       "expoProdNm": "오디세이(4DX 2D)",
//       "engProdNm": "(4DX 2D)The Odyssey",
//       "prodNm": "오디세이(4DX 2D)",
//       "movkndCd": "08",
//       "movkndDsplNm": "4DX 2D",
//       "movkndDsplEnm": "4DX 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "01",
//       "salsTznNm": "모닝",
//       "scnsrtTm": "0940",
//       "scnendTm": "1242",
//       "salEndTm": "0955",
//       "sascnsGradCd": "01",
//       "sortOseq": "2",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "02",
//       "tcscnsGradNm": "4DX",
//       "stcnt": "144",
//       "cpSeatCnt": "144",
//       "frSeatCnt": "3",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "4",
//       "movfNo": "50002596",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0201",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "7",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "0950",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "003",
//       "scnsNm": "4DX관",
//       "expoScnsNm": "4DX관",
//       "scnsEnm": "4DX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "4",
//       "prodNo": "20054744",
//       "expoProdNm": "오디세이(4DX 2D)",
//       "engProdNm": "(4DX 2D)The Odyssey",
//       "prodNm": "오디세이(4DX 2D)",
//       "movkndCd": "08",
//       "movkndDsplNm": "4DX 2D",
//       "movkndDsplEnm": "4DX 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "1620",
//       "scnendTm": "1922",
//       "salEndTm": "1635",
//       "sascnsGradCd": "01",
//       "sortOseq": "2",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "02",
//       "tcscnsGradNm": "4DX",
//       "stcnt": "144",
//       "cpSeatCnt": "144",
//       "frSeatCnt": "58",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "4",
//       "movfNo": "50002596",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0201",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "62",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1630",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "018",
//       "scnsNm": "IMAX관",
//       "expoScnsNm": "IMAX관",
//       "scnsEnm": "IMAX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "1",
//       "prodNo": "20054745",
//       "expoProdNm": "오디세이(IMAX LASER 2D)",
//       "engProdNm": "(IMAX LASER 2D)The Odyssey",
//       "prodNm": "오디세이(IMAX LASER 2D)",
//       "movkndCd": "48",
//       "movkndDsplNm": "IMAX LASER 2D",
//       "movkndDsplEnm": "IMAX LASER 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "01",
//       "salsTznNm": "모닝",
//       "scnsrtTm": "0630",
//       "scnendTm": "0932",
//       "salEndTm": "0645",
//       "sascnsGradCd": "01",
//       "sortOseq": "3",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "03",
//       "tcscnsGradNm": "아이맥스",
//       "stcnt": "624",
//       "cpSeatCnt": "624",
//       "frSeatCnt": "4",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "6",
//       "movfNo": "50002600",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0301",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "8",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "0640",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "018",
//       "scnsNm": "IMAX관",
//       "expoScnsNm": "IMAX관",
//       "scnsEnm": "IMAX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "2",
//       "prodNo": "20054745",
//       "expoProdNm": "오디세이(IMAX LASER 2D)",
//       "engProdNm": "(IMAX LASER 2D)The Odyssey",
//       "prodNm": "오디세이(IMAX LASER 2D)",
//       "movkndCd": "48",
//       "movkndDsplNm": "IMAX LASER 2D",
//       "movkndDsplEnm": "IMAX LASER 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "01",
//       "salsTznNm": "모닝",
//       "scnsrtTm": "1000",
//       "scnendTm": "1302",
//       "salEndTm": "1015",
//       "sascnsGradCd": "01",
//       "sortOseq": "3",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "03",
//       "tcscnsGradNm": "아이맥스",
//       "stcnt": "624",
//       "cpSeatCnt": "624",
//       "frSeatCnt": "4",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "6",
//       "movfNo": "50002600",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0301",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "8",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1010",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "018",
//       "scnsNm": "IMAX관",
//       "expoScnsNm": "IMAX관",
//       "scnsEnm": "IMAX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "3",
//       "prodNo": "20054745",
//       "expoProdNm": "오디세이(IMAX LASER 2D)",
//       "engProdNm": "(IMAX LASER 2D)The Odyssey",
//       "prodNm": "오디세이(IMAX LASER 2D)",
//       "movkndCd": "48",
//       "movkndDsplNm": "IMAX LASER 2D",
//       "movkndDsplEnm": "IMAX LASER 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "1330",
//       "scnendTm": "1632",
//       "salEndTm": "1345",
//       "sascnsGradCd": "01",
//       "sortOseq": "3",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "03",
//       "tcscnsGradNm": "아이맥스",
//       "stcnt": "624",
//       "cpSeatCnt": "624",
//       "frSeatCnt": "18",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "6",
//       "movfNo": "50002600",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0301",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "22",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1340",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "018",
//       "scnsNm": "IMAX관",
//       "expoScnsNm": "IMAX관",
//       "scnsEnm": "IMAX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "4",
//       "prodNo": "20054745",
//       "expoProdNm": "오디세이(IMAX LASER 2D)",
//       "engProdNm": "(IMAX LASER 2D)The Odyssey",
//       "prodNm": "오디세이(IMAX LASER 2D)",
//       "movkndCd": "48",
//       "movkndDsplNm": "IMAX LASER 2D",
//       "movkndDsplEnm": "IMAX LASER 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "1700",
//       "scnendTm": "2002",
//       "salEndTm": "1715",
//       "sascnsGradCd": "01",
//       "sortOseq": "3",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "03",
//       "tcscnsGradNm": "아이맥스",
//       "stcnt": "624",
//       "cpSeatCnt": "624",
//       "frSeatCnt": "33",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "6",
//       "movfNo": "50002600",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0301",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "37",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "1710",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "018",
//       "scnsNm": "IMAX관",
//       "expoScnsNm": "IMAX관",
//       "scnsEnm": "IMAX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "5",
//       "prodNo": "20054745",
//       "expoProdNm": "오디세이(IMAX LASER 2D)",
//       "engProdNm": "(IMAX LASER 2D)The Odyssey",
//       "prodNm": "오디세이(IMAX LASER 2D)",
//       "movkndCd": "48",
//       "movkndDsplNm": "IMAX LASER 2D",
//       "movkndDsplEnm": "IMAX LASER 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "2030",
//       "scnendTm": "2332",
//       "salEndTm": "2045",
//       "sascnsGradCd": "01",
//       "sortOseq": "3",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "03",
//       "tcscnsGradNm": "아이맥스",
//       "stcnt": "624",
//       "cpSeatCnt": "624",
//       "frSeatCnt": "10",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "6",
//       "movfNo": "50002600",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0301",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "14",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "2040",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     },
//     {
//       "coCd": "A420",
//       "siteNo": "0013",
//       "siteNm": "CGV 용산아이파크몰",
//       "scnsNo": "018",
//       "scnsNm": "IMAX관",
//       "expoScnsNm": "IMAX관",
//       "scnsEnm": "IMAX",
//       "atktPsblQty": "8",
//       "scnYmd": "20260805",
//       "scnSseq": "6",
//       "prodNo": "20054745",
//       "expoProdNm": "오디세이(IMAX LASER 2D)",
//       "engProdNm": "(IMAX LASER 2D)The Odyssey",
//       "prodNm": "오디세이(IMAX LASER 2D)",
//       "movkndCd": "48",
//       "movkndDsplNm": "IMAX LASER 2D",
//       "movkndDsplEnm": "IMAX LASER 2D",
//       "cratgClsCd": "02",
//       "cratgClsNm": "15세이상관람가",
//       "salsTznCd": "26",
//       "salsTznNm": "일반",
//       "scnsrtTm": "2400",
//       "scnendTm": "2702",
//       "salEndTm": "2415",
//       "sascnsGradCd": "01",
//       "sortOseq": "3",
//       "sascnsGradNm": "일반",
//       "tcscnsGradCd": "03",
//       "tcscnsGradNm": "아이맥스",
//       "stcnt": "624",
//       "cpSeatCnt": "624",
//       "frSeatCnt": "195",
//       "cntlYn": "N",
//       "crntrvDsplYn": "N",
//       "hotdlYn": "N",
//       "dblfrNo": null,
//       "dblfrRpsntYn": null,
//       "iceconYn": "N",
//       "arthsYn": "N",
//       "srlsYn": "N",
//       "childnMovYn": "N",
//       "movclsCd": "01",
//       "movclsNm": "영화",
//       "speclIndctTypCd": "01",
//       "movTirCd": "01",
//       "siteGradCd": "01",
//       "srvltKindCd": "01",
//       "slddKindCd": "01",
//       "sesnNo": null,
//       "movNo": "30001323",
//       "movNm": "오디세이",
//       "movEnm": "The Odyssey",
//       "mvSeatCnt": "6",
//       "movfNo": "50002600",
//       "bzplcNo": "0013001",
//       "vatincYn": "Y",
//       "prdtypCd": "01",
//       "prddtlTypCd": "0101",
//       "prdcmpTypCd": "01",
//       "cxprdYn": "N",
//       "scnsGradCd": "0301",
//       "prcrulDivCd": "01",
//       "videoAddexpCd": null,
//       "videoAddexpCdNm": null,
//       "videoAddexpCont": null,
//       "sbtdivCd": null,
//       "sbtdivNm": null,
//       "physcFnm": "30001323_185.jpg",
//       "physcFilePathnm": "030001/30001323/30001323_185.jpg",
//       "frtmpSeatCnt": "199",
//       "hotdlDtlNo": null,
//       "rlMovStartTm": "2410",
//       "prmddNo": null,
//       "prmddNm": null,
//       "prodImg": null,
//       "cndProdYn": null,
//       "cndsaTypCd": null,
//       "cndSalYnList": null
//     }
//   ]
// }